### PR TITLE
Merge QEMU v7.2.4

### PR DESCRIPTION
**Pull request by mborgerson**
Updates as of 7/17/23:
* Dashboard audio issue root caused to upstream QEMU regression. Patch for the issue added to this PR, and sent upstream.
* Confirmed hang issue with PGR2. Root caused to upstream QEMU regression in 7.2.0, that was fixed in ff50379. Cherry-picked upstream patch.
* Fixed issue preventing snapshot load.
* Merged xemu master branch updates.
* Cherry-picked upstream glib build fix.
* Arctic Thunder and Forza seem to be consistent with current `master` build.
* Merged QEMU v7.2.0..v7.2.4 updates. No additional conflicts.

Notes:
* UnleashX, LithiumX dashboard does not properly list files on F: (Issue reported via Kevin:)
   * Before this PR xemu was incorrectly reporting number of drive sectors in `ATA IDENTIFY DEVICE` command output words 60-61. It should be capped at 28b per ATA spec, with LBA48 reported in words 100-103. BIOSes were happily accepting this flawed reporting. It was fixed in 46e018e9b741731842b93ce23a86fad60445969b.

### CODE REVIEW

**Comment by HadetTheUndying** [comment]
So far I've tested reported **Perfect** games. Most games are seeing a noticeable performance boost in MSPF. Some games at between 1x-6x scaling on my hardware I'm getting sub 10ms per frame.

I was experiencing a hard lock in Phantom Crash that I was able to reproduce by allowing myself to be shot, however when I rebooted my PC I was no longer able to reproduce this issue and the game was running perfectly. I think someone else should still test this case, regardless

I had Azurik freeze, but not the emulator which is not uncommon for Azurik but i figured I'd report it anyway.

I've also tested but not extensively:

- Adding XMUs
- Adding `usb-kbd`
- Taking and loading disc snapshots

Build Info:

```
Version:      0.7.79-10324-g7cbe9d337a
Branch:       sync/qemu-7.2.0
Commit:       7cbe9d337a89462016073e17122242151247ae61
Date:         Mon Jan 23 09:20:03 PM UTC 2023
```

System Info:

```
CPU:          AMD Ryzen 7 2700X Eight-Core Processor         
OS Platform:  Linux
OS Version:   Void Linux
Manufacturer: AMD
GPU Model:    AMD Radeon RX Vega (vega10, LLVM 12.0.1, DRM 3.48, 6.0.19_1)
Driver:       4.6 (Core Profile) Mesa 22.3.2
Shader:       4.60
```

Config Info:

```
MCPX Boot ROM MD5 Hash:        d49c52a4102f6df7bcf8d0617ac475ed
Flash ROM (BIOS) MD5 Hash:     21445c6f28fca7285b0f167ea770d1e5
```

EDIT:

I was also able to connect to Insignia without issue using NAT Network mode, including communicating with other players in PSO.

**Comment by mborgerson** [comment]
Open issues
---

Via Jenci:
Juiced -> "there's dirty disc [...]" after loaded the save file
Forza Motorsport -> hangs at loading screen before ingame

Via Kevin:
UnleashX dashboard does not properly list files on E:\

**Comment by ryzendew** [comment]
Dragons Lair 3D (https://user-images.githubusercontent.com/84041391/214200333-5d86958d-3844-468a-bd3e-30c67d7a3ad1.png) 

Even bigger performance loss went from 20fps on master to 7-10fps without scaling..

`Version:      0.7.83-10326-g91302dedd5
Branch:       
Commit:       91302dedd574a74a827018126c6b31a66bb8f908
Date:         Mon Jan 23 20:09:54 UTC 2023`

`CPU:          AMD Ryzen 7 5800H       
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2
Driver:       4.0.0 NVIDIA 527.86
Shader:       4.00 NVIDIA via Cg compiler`

https://user-images.githubusercontent.com/84041391/214201663-fc5200d2-d60b-4683-bca2-8b0f3b5682e3.png
Half-life 2 hangs when going in game before g-man starts to talk. 

https://user-images.githubusercontent.com/84041391/214202218-7cdb4444-cac7-41a9-8314-f331d0cfa126.png
doom 3 hangs in game after a few mins and master build is normal no freezing.

**Comment by HadetTheUndying** [comment]
> ![image](https://user-images.githubusercontent.com/84041391/214200333-5d86958d-3844-468a-bd3e-30c67d7a3ad1.png.
> 
> Even bigger performance loss went from 20fps to 7-10fps without scaling on this game used to be 60fps.
> 
> `Version: 0.7.83-10326-g91302dedd5 Branch: Commit: 91302dedd574a74a827018126c6b31a66bb8f908 Date: Mon Jan 23 20:09:54 UTC 2023`
> 
> `CPU: AMD Ryzen 7 5800H OS Platform: Windows OS Version: Windows Manufacturer: NVIDIA Corporation GPU Model: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 Driver: 4.0.0 NVIDIA 527.86 Shader: 4.00 NVIDIA via Cg compiler`

Dragon's Lair 3D? I recall having pretty bad performance in this game on master with AMD.

**Comment by ryzendew** [comment]
> > ![image](https://user-images.githubusercontent.com/84041391/214200333-5d86958d-3844-468a-bd3e-30c67d7a3ad1.png.
> > Even bigger performance loss went from 20fps to 7-10fps without scaling on this game used to be 60fps.
> > `Version: 0.7.83-10326-g91302dedd5 Branch: Commit: 91302dedd574a74a827018126c6b31a66bb8f908 Date: Mon Jan 23 20:09:54 UTC 2023`
> > `CPU: AMD Ryzen 7 5800H OS Platform: Windows OS Version: Windows Manufacturer: NVIDIA Corporation GPU Model: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 Driver: 4.0.0 NVIDIA 527.86 Shader: 4.00 NVIDIA via Cg compiler`
> 
> Dragon's Lair 3D? I recall having pretty bad performance in this game on master with AMD.

AMD GPU i am using a 3070 and on the master build it's 20fps and on a way older build it''s 60fps fine

**Comment by mborgerson** [comment]
@RyzenDew only comparisons against latest release of xemu are relevant. 'way older build' is not helpful in this case. Can you compare this PR against latest release of xemu (master branch)?

**Comment by ryzendew** [comment]
> @RyzenDew only comparisons against latest release of xemu are relevant. 'way older build' is not helpful in this case. Can you compare this PR against latest release of xemu (master branch)?

ya and i told you 20fps on the newest build

**Comment by jenci8888** [comment]
Juiced -> "there's dirty disc [...]" after loaded the save file
Forza Motorsport -> hangs at loading screen before ingame
Project Gotham Racing 2 -> Hangs at pre-race or rolling start (shortly ingame)

**Comment by RyzenDew** [comment]
image
Half-life 2 hangs when going in game before g-man starts to talk.

**Comment by RyzenDew** [comment]
image
doom 3 hangs in game after a few mins and master build is normal no freezing.

**Comment by mborgerson** [comment]
Note to testers: Please use/edit original comment to post updates as you try different games

**Comment by arronh4599** [comment]
https://user-images.githubusercontent.com/95377747/214269233-914ab557-5e26-40b0-9c9e-845cf5f7eba5.mp4
Music player on the dashboard has audio screeching. Tried the master build and it's fine there.

**Comment by arronh4599** [comment]
https://user-images.githubusercontent.com/95377747/214273476-d26def2c-30ea-400e-8bfb-f0bbb240a85d.mp4

Audio glitch in the music player. xemu_version: 0.7.83-10326-g91302dedd5 
Checked the previous version of xemu, v0.7.8.3 and the sound is fine there.

**Comment by LeRutY** [comment]
Audio glitch also happening in Project Gotham Racing 2. Performance is the same in this build

**Comment by mborgerson** [comment]
Confirmed dashboard soundtrack playback audio bug.

**Comment by ehw** [comment]
I tested a few games from my collection. Hope this helps. The only real change I saw was that there seems to be audio issues in Arctic Thunder's FMVs. Other than that, it seems to run the same. I don't think I noticed performance improvements either...

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/knuck/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/knuck/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Game Name | Notes | Changes
-- | -- | --
Arctic Thunder (USA) |   | Audio issues during opening FMV, not present in main branch
ATV - Quad Power Racing 2 (USA) |   | Maybe some small audio issues during opening FMV
Auto Modellista (USA, Japan) | No change. | No change.
Black Stone - Magic & Steel (USA,   Europe) | Issue 904, 979, 1220 not fixed | No change.
Blinx - The Time Sweeper (USA) (En,Ja)   (Rev 1) |   | No change.
Blinx 2 - Masters of Time & Space ~   Blinx 2 - Battle of Time & Space (World) (En,Ja,Fr,De,Es,It) |   | No change.
Bloody Roar - Extreme (USA) | Game still has severe performance issues during matches. | No change.
Burnout 3 - Takedown (USA) |   | No change.
Carve (USA, Europe) (En,Fr,De,Es,It) |   | No change.
Crazy Taxi 3 - High Roller (USA) | Issue 1404 not fixed | No change, shader generation slower?



</body>

</html>


Tested some more games. I think the only thing of note is that Puyo Pop Fever doesn't seem to load after pressing start at the title screen but this might've been resolved with v0.7.84.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/knuck/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/knuck/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Game Name | Notes | Changes
-- | -- | --
Cel Damage (USA) | No issues. Performance issues were apparently reported but none exist in   main or this branch. | None
Conker - Live & Reloaded (USA)   (En,Ja,Fr,De,Es,It) | FMVs are still a little choppy, possible Z-fighting issues remain, no   idea if segfaults remain. | None
Dead or Alive 1 Ultimate (USA, Japan)   (En,Ja) | Game still suffers from performance issues in matches. | None
Dead or Alive 2 Ultimate (USA, Japan)   (En,Ja) | Game still suffers from performance issues in matches on certain stages. | None
Dead or Alive 3 (USA) (En,Ja) | Game still suffers from performance issues in matches on certain stages. | None
Dead or Alive Xtreme Beach Volleyball   (USA) (En,Ja) | No issues. | None.
Fatal Frame (USA) | No issues. | None.
Fatal Frame II - Crimson Butterfly -   Director's Cut (USA) | Issues 1264 and 549 are still occurring. | None.
Futurama (USA) | Issue 1393 is still occurring. | It seems even the video in FMVs are starting to skip now, rather than   just the audio.
Gauntlet - Dark Legacy (USA) | No issues. | None.
Group S Challenge (USA) | Issue 1410 is still occurring, game crashes with an Assertion failed!   Message when starting races. | None.
Gun Valkyrie (USA) (En,Ja) | No issues. | None.
Gungriffon - Allied Strike (USA, Japan)   (En,Ja,Ko) | Game still has laggy FMVs, and the game runs with an uncapped framerate   which might've not been in the original (1011). However, game seems to   perform better in this branch. | Better performance it seems?
Halo - Combat Evolved (USA) (Rev 2) | No issues. | None.
Halo 2 (USA, Europe)   (En,Ja,Fr,De,Es,It,Zh,Ko) | No issues. | None.
Harry Potter and the Chamber of Secrets   (USA) | No issues. | None.
House of the Dead III, The (USA) | No issues. | None.
JSRF - Jet Set Radio Future (USA) | 339, 1256, 621 are still issues. | None.
Mad Dash Racing (USA) | No issues. | None.
MechAssault (USA) (En,Fr,De) (Rev 1) | No issues. | None.
MechAssault 2 - Lone Wolf (World)   (En,Ja,Fr,De,Es,It) | Issue 1022 still exists, game isn't playable. | None.
Metal Wolf Chaos (Japan) | No issues. Issue 400 might be due to bad drivers. Can't reproduce. | None.
Midway Arcade Treasures (USA, Europe) | No issues. | None.
Midway Arcade Treasures 2 (USA, Europe) | No issues. | None.
Midway Arcade Treasures 3 (USA, Europe) | No issues. Game might randomly hang in both main and pr, not sure if   reported. | None.
Murakumo - Renegade Mech Pursuit (USA) | Issue 1025 still occurring. | None.
OutRun 2 (USA) | No issues. | None.
OutRun 2006 - Coast 2 Coast (USA, Europe)   (En,Fr,De,Es,It) | No issues. | None.
Panzer Dragoon Orta (USA) | No issues. I'm not seeing performance issues as suggested by issue 1163   on pr and main. | None.
Phantom Crash (USA) | No issues. | None.
Puyo Pop Fever (Europe)   (En,Ja,Fr,De,Es,It) | Game seems to have some weird minor performance issues, game never runs   full framerate in both pr and main. | Hangs on loading screen after pressing start at title screen. Might have   been resolved with v0.7.84? Works fine on main.



</body>

</html>

Xbox Live works too. Tested with Phantasy Star Online (game is still pretty slow).4

I also noticed that [v8.0.0-rc0](https://github.com/qemu/qemu/releases/tag/v8.0.0-rc0) of QEMU came out today, so I guess v8's release is around the corner?

Testing is being done with the following:
Version:      0.7.83-10326-g91302dedd5
Branch:       
Commit:       91302dedd574a74a827018126c6b31a66bb8f908
Date:         Mon Jan 23 20:09:54 UTC 2023

CPU:          AMD Ryzen 7 5800X 8-Core Processor             
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver:       4.0.0 NVIDIA 531.29
Shader:       4.00 NVIDIA via Cg compiler

**Comment by mborgerson** [comment]
Thanks for testing, @ehw! The audio introduced by this PR are known and I do plan to fix them soon.

**Comment by ehw** [comment]
Tested some more games. I think the only thing of note is that Puyo Pop Fever doesn't seem to load after pressing start at the title screen but this might've been resolved with v0.7.84.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/knuck/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/knuck/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Game Name | Notes | Changes
-- | -- | --
Cel Damage (USA) | No issues. Performance issues were apparently reported but none exist in   main or this branch. | None
Conker - Live & Reloaded (USA)   (En,Ja,Fr,De,Es,It) | FMVs are still a little choppy, possible Z-fighting issues remain, no   idea if segfaults remain. | None
Dead or Alive 1 Ultimate (USA, Japan)   (En,Ja) | Game still suffers from performance issues in matches. | None
Dead or Alive 2 Ultimate (USA, Japan)   (En,Ja) | Game still suffers from performance issues in matches on certain stages. | None
Dead or Alive 3 (USA) (En,Ja) | Game still suffers from performance issues in matches on certain stages. | None
Dead or Alive Xtreme Beach Volleyball   (USA) (En,Ja) | No issues. | None.
Fatal Frame (USA) | No issues. | None.
Fatal Frame II - Crimson Butterfly -   Director's Cut (USA) | Issues 1264 and 549 are still occurring. | None.
Futurama (USA) | Issue 1393 is still occurring. | It seems even the video in FMVs are starting to skip now, rather than   just the audio.
Gauntlet - Dark Legacy (USA) | No issues. | None.
Group S Challenge (USA) | Issue 1410 is still occurring, game crashes with an Assertion failed!   Message when starting races. | None.
Gun Valkyrie (USA) (En,Ja) | No issues. | None.
Gungriffon - Allied Strike (USA, Japan)   (En,Ja,Ko) | Game still has laggy FMVs, and the game runs with an uncapped framerate   which might've not been in the original (1011). However, game seems to   perform better in this branch. | Better performance it seems?
Halo - Combat Evolved (USA) (Rev 2) | No issues. | None.
Halo 2 (USA, Europe)   (En,Ja,Fr,De,Es,It,Zh,Ko) | No issues. | None.
Harry Potter and the Chamber of Secrets   (USA) | No issues. | None.
House of the Dead III, The (USA) | No issues. | None.
JSRF - Jet Set Radio Future (USA) | 339, 1256, 621 are still issues. | None.
Mad Dash Racing (USA) | No issues. | None.
MechAssault (USA) (En,Fr,De) (Rev 1) | No issues. | None.
MechAssault 2 - Lone Wolf (World)   (En,Ja,Fr,De,Es,It) | Issue 1022 still exists, game isn't playable. | None.
Metal Wolf Chaos (Japan) | No issues. Issue 400 might be due to bad drivers. Can't reproduce. | None.
Midway Arcade Treasures (USA, Europe) | No issues. | None.
Midway Arcade Treasures 2 (USA, Europe) | No issues. | None.
Midway Arcade Treasures 3 (USA, Europe) | No issues. Game might randomly hang in both main and pr, not sure if   reported. | None.
Murakumo - Renegade Mech Pursuit (USA) | Issue 1025 still occurring. | None.
OutRun 2 (USA) | No issues. | None.
OutRun 2006 - Coast 2 Coast (USA, Europe)   (En,Fr,De,Es,It) | No issues. | None.
Panzer Dragoon Orta (USA) | No issues. I'm not seeing performance issues as suggested by issue 1163   on pr and main. | None.
Phantom Crash (USA) | No issues. | None.
Puyo Pop Fever (Europe)   (En,Ja,Fr,De,Es,It) | Game seems to have some weird minor performance issues, game never runs   full framerate in both pr and main. | Hangs on loading screen after pressing start at title screen. Might have   been resolved with v0.7.84? Works fine on main.



</body>

</html>

I'll set up Xbox Live and see if that's still working too.

**Comment by mborgerson** [comment]
See updated PR description for notes.

@arronh4599 @ehw @LeRutY , would you please help confirm any game audio issues (that were introduced previously with this PR) are now resolved for you?

**Pull request merged**
