### PR TITLE
nv2a: (Probably partial) handling for `1D7C`

### LINKED ISSUE #1162: Tenchu Return from Darkness - Wireframes Everywhere.
### Title

https://xemu.app/titles/41560026/#Tenchu-Return-from-Darkness

### Bug Description

Wireframe appears on characters and scenery while in-game. You notice it once you get to the character select screen. The wireframes are not textures seams and they stay solid regardless of the camera angle.

Higher-resolution scaling decreases the size of the wireframe lines. 

unknown

### Expected Behavior

Wireframes shouldn't appear at all.

### xemu Version

Version:      0.7.57
Branch:       master
Commit:       6a8a967438572656e95d12b881eb01f0f1873aaa
Date:         Sat Jul  2 17:42:25 UTC 2022

### System Information

CPU:          AMD Ryzen 9 5900X 12-Core Processor            
OS Platform:  Windows
OS Version:   Windows
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver:       4.0.0 NVIDIA 516.59
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

I noticed this issue at least over a year ago.

### LINKED ISSUE #1176: MagiDeathFight! Nivida rendering issue
### Title

https://xemu.app/titles/544b0001/#Magi-Death-Fight

### Bug Description

When using a Nivida GPU to test this game, all menu screens have a diagonal line going across the whole screen from corner to corner. This didn't affect me when using an AMD GPU but think it is an Ampere issue only.
xemu-2022-07-08-14-53-58

### Expected Behavior

The line should'nt be present

### xemu Version

Version: 0.7.58
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/6f878ede01ad1992392dde22b506a3c00fab87c4
Date: Wed Jul 6 02:14:58 UTC 2022

### System Information

<html><body>

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processor
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

</body>
</html>

### Additional Context

_No response_

### LINKED ISSUE #1225: King Arthur Graphical Issue
### Title

https://xemu.app/titles/4b4e0024/#King-Arthur

### Bug Description

The wheels have some black lines it doesn't appear on the hardware
xemu-2022-08-06-01-09-51

### Expected Behavior

https://youtu.be/hBEkYhtiee4?t=139

### xemu Version

xemu Version

Version: 0.7.66
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/c2031108c5990d10173cd4d71b23b06b395d682a
Date: Mon Jul 25 17:47:29 UTC 2022

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Implements handling for the unknown 0x1D7C command in order to match observed
behavior in the MS Dashboard and Tenchu: Return from Darkness.

Setting 1D7C's low bit appears to disable the line and poly smoothing commands.

Fixes #1162
Fixes #1176 
Fixes #1225

[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/three_d_primitive_tests.cpp)
[HW Results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-3D_primitive)

[Additional test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/smoothing_tests.cpp)
[Additional results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Smoothing_control)

### CODE REVIEW

**Comment by Triticum0** [comment]
Tested MagiDeathFight! issue seems to be unrelated

**Comment by Triticum0** [comment]
Yeah, It fixes #1176 good job!!! It has other issues mentioned in #679 if you are interested in another log. 

Thank you for all the hard work you do for the community. =)

**Comment by abaire** [comment]
> Yeah, It fixes #1176 good job!!! It has other issues mentioned in #679 if you are interested in another log.
> 
> Thank you for all the hard work you do for the community. =)

Excellent, thanks for testing!

**Comment by Triticum0** [comment]
Fixes #1225

**Comment by Reonu** [comment]
Would love to see this merged so that Tenchu looks ok

**Review by Reonu — APPROVED** [review]

**Comment by mborgerson** [comment]
Confirmed! Apologies for the lengthy review delay, and thanks for the fix!

**Pull request merged**
