### PR TITLE
ci: Generate AppImage

### LINKED ISSUE #1103: Build AppImage releases
### Feature Request

It would be nice if xemu released AppImage versions for Linux. It's something we can easily do in the CI pipeline to provide consistent/reproducible/portable releases to people running different distributions.

### Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mborgerson**
Closes #1103

### CODE REVIEW

**Comment by j8r** [comment]
We can then use this same file for the Flatpak.
Also note that `appdata.xml` extenaion has been deprecates in favor of `metainfo.xml`, see https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html.

**Comment by j8r** [comment]
We can then use this same file for the Flatpak.
Also note that `appdata.xml` extension has been deprecated in favor of `metainfo.xml`, see https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html.

**Comment by mborgerson** [comment]
> We can then use this same file for the Flatpak. Also note that `appdata.xml` extension has been deprecated in favor of `metainfo.xml`, see https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html.

Yeah definitely, although I don't know if flathub requires up to date releases section, and I don't want to create extra churn to track it on xemu master branch if so

And appimage packing apparently expects appdata.xml. Since both are accepted generally, we'll just go with appdata.xml until appimage tools advance

**Comment by j8r** [comment]
Where to host the screenshots? I think they can have their place on the website too, then we will be able to use their URL on the appdata file.

**Comment by mborgerson** [comment]
xemu-website seems like a reasonable spot for the screenshots to live

**Pull request merged**
