### PR TITLE
xemu: Update Copyright Year

### PR DESCRIPTION
**Pull request by MasonT8198**
Same as commit 6e564854fc03266cabb59e01010ea5d20ebd03c5 but updating the year again!

### CODE REVIEW

**Comment by mborgerson** [comment]
Based on `grep -rPe "202\d\s+Matt"` there should be at least 70 files that need an update. Can you update the others?

Also no need to change the case of the 'C' in (C). Just the year number range can be updated (never changing the start year, only adding a -2022 or updating a -2021 to -2022)

**Comment by MasonT8198** [comment]
> Based on `grep -rPe "202\d\s+Matt"` there should be at least 70 files that need an update. Can you update the others?
> 
> Also no need to change the case of the 'C' in (C). Just the year number range can be updated (never changing the start year, only adding a -2022 or updating a -2021 to -2022)

Yeah my bad on changing the cases, I just ran a quick find and replace command

**Comment by mborgerson** [comment]
If you can, please update the remaining files and we will merge this

**Comment by MasonT8198** [comment]
Closing this on the account of seemingly not having enough spare time to finish this, however will open with this completed if I find the time

FTR; maybe just biting the bullet and automating this process is the best idea

**Pull request closed without merging**
