### PR TITLE
nv2a: Invalidate zeta when constructing non-matching color surface.

### LINKED ISSUE #420: Failed assertion of bound surface size comparison
### Title

https://xemu.app/titles/4c41001a/#Star-Wars-Battlefront-II
https://xemu.app/titles/49470017/#Gun-Valkyrie

### Bug Description

Starting a split Screen Instant Action game crashes the emulator with 
xemu: ../hw/xbox/nv2a/pgraph.c:5598: pgraph_update_surface: Assertion `(pg->color_binding->width == pg->zeta_binding->width) && (pg->color_binding->height == pg->zeta_binding->height)' failed.
Aborted (core dumped)
Capture
Happens on latest version of xemu on both Lubuntu 21.04 and Windows 11 Preview

### Expected Behavior

Split Screen matches are supposed to go in game with playable fps.

### xemu Version

Version: 0.5.4-39-gedf3735718

### System Information

OS: Lubuntu 21.04 and Windows 11 Preview
CPU: Intel Core i5 8600K
GPU:AMD Radeon RX6800
GPU Driver:Mesa 21.3.0-devel and Radeon Software 21.7.1

### Additional Context

_No response_

### LINKED ISSUE #841: Juiced: Game is now Broken, Does not start
### Title

https://xemu.app/titles/545100ef/#Juiced

NTSC

### Bug Description

Assert Error on Game booting: hw/xbox/nv2a/pgraph.c Line 5992. Was previously playable, became broke starting on xemu 0.5.4-39-gedf3735718 on 07-20-21

### Expected Behavior

Game should boot and play.

### xemu Version

Problem started on xemu 0.5.4-39-gedf3735718 07-20-21. Previous to that the game was playable. 

### System Information

OS: Windows 10
CPU: AMD Ryzen 9 5950X
GPU: GTX 1070

### Additional Context

Will add a log later.

### LINKED ISSUE #931: SoulCalibur II: Crash on Launch
### Title

https://xemu.app/titles/4e4d0003/#Soulcalibur-II

### Bug Description

Launching SoulCalibur II crashes Xemu; GDB throws a message about what might have caused it?
```
xemu: ../hw/xbox/nv2a/pgraph.c:6039: void pgraph_update_surface(NV2AState *, _Bool, _Bool, _Bool): Assertion `(pg->color_binding->width == pg->zeta_binding->width) && (pg->color_binding->height == pg->zeta_binding->height)' failed.
```

### Expected Behavior

Attempting to run SoulCalibur II should not crash Xemu

### xemu Version

Version:      0.7.13
Branch:       master
Commit:       38a0e46f8c59c6da50029c1b53712070f211ac74
Date:         Wed May 18 09:10:05 PM UTC 2022
Compiler: Clang 13.0.1 (Xemu compiled with full LTO)
Compiler flags ([via makepkg](https://wiki.archlinux.org/title/Makepkg)):
```
CC=clang
CXX=clang++
LD="/usr/bin/ld.lld"
CC_LD="/usr/bin/ld.lld"
CXX_LD="/usr/bin/ld.lld"
AR="/usr/bin/llvm-ar"
NM="/usr/bin/llvm-nm"
AS="/usr/bin/llvm-as"
RANLIB="/usr/bin/llvm-ranlib"
STRIP="/usr/bin/llvm-strip"
OBJCOPY="/usr/bin/llvm-objcopy"

CFLAGS="-march=znver2 -mtune=znver2 -O3 -pipe -fno-plt -fexceptions -Wall \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O3,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=full"
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="${DEBUG_CFLAGS}"
```

### System Information

CPU:          AMD Ryzen 7 3700X 8-Core Processor             
OS Platform:  Linux
OS Version:   Arch Linux
Kernel: [Linux 5.17.2-256-tkg-pds-llvm](https://github.com/frogging-family/linux-tkg)
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
Driver:       4.0.0 NVIDIA 510.60.02
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

[Compiled via the AUR](https://aur.archlinux.org/packages/xemu-git)

[GDB core dump](https://mega.nz/file/4zZWFLoL#KzgFGbuiQfYHtdvotQDT9xmeLRvBAX4m9EWhkfre9ac) - (file size is too big for github)
[xemu-SC2-gdb.log](https://github.com/mborgerson/xemu/files/8721279/xemu-SC2-gdb.log)

### PR DESCRIPTION
**Pull request by abaire**
Fixes #420 
Fixes #841 
Fixes #931 

[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/surface_clip_tests.cpp)
[HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Surface_clip)

Note that HW results differ substantially from xemu due to the fact that xemu treats the color surface format as the definitive output whereas this seems to be configured separately on nv2a (it's possible to instruct the HW to write to the backbuffer in R5G5B5 format but still display the content as ARGB, resulting in a squashed, color shifted framebuffer).

### CODE REVIEW

**Comment by vanderleivieirainacio** [comment]
Also fixes crashes in loading Sonic Heroes!

Captura de tela 2022-05-19 182111

Captura de tela 2022-05-19 182923

**Comment by vanderleivieirainacio** [comment]
Also fixes crashes in Van Helsing's loadout!

Captura de tela 2022-05-19 185737

Captura de tela 2022-05-19 185819

Captura de tela 2022-05-19 185857

**Comment by abaire** [comment]
> Also fixes crashes in Van Helsing's loadout!

I believe that should've already been fixed by #933 which was included in 0.7.14

**Comment by abaire** [comment]
> Also fixes crashes in loading Sonic Heroes!

@vanderleivieirainacio is that the issue tracked in #434 ? From the history in that bug it seems like it's not always reproducible which makes me dubious that this PR fixes it. 

If you can confirm that #434 is still broken on 0.7.15 and using just this PR fixes the problem I'm happy to mark it as fixed so it gets closed when this is merged.

**Comment by vanderleivieirainacio** [comment]
> > Also fixes crashes in loading Sonic Heroes!
> 
> @vanderleivieirainacio is that the issue tracked in #434 ? From the history in that bug it seems like it's not always reproducible which makes me dubious that this PR fixes it.
> 
> If you can confirm that #434 is still broken on 0.7.15 and using just this PR fixes the problem I'm happy to mark it as fixed so it gets closed when this is merged.

You're right, both Van Helsing and Sonic Heroes are already fixed in version 0.7.15 my friend. It was my mistake, I should have checked earlier. Well, Van Helsing and Sonic Heroes work now, no breakages. Thanks for the work friend.

**Comment by mborgerson** [comment]
> Note that HW results differ substantially from xemu due to the fact that xemu treats the color surface format as the definitive output whereas this seems to be configured separately on nv2a (it's possible to instruct the HW to write to the backbuffer in R5G5B5 format but still display the content as ARGB, resulting in a squashed, color shifted framebuffer).

We could emulate this behavior, but for now let's ignore this pathological case :)

**Comment by Triticum0** [comment]
You missed this #694

**Pull request merged**
