### PR TITLE
ci: Build for Windows with clang/LLVM toolchain, support ARM64

### LINKED ISSUE #791: Windows ARM support
### Feature Request

Howdy! I wanted to say that the work done by the XEMU developers is truly amazing, being able to launch XBOX on my Mac is truly something I did not picture ever happening <3

Since the MAC version is universal, made me wonder about ARM as a whole... It would mean a lot if you could consider adding ARM64 support for Windows devices. Or, at the very least consider making a compiler on ARM so that we can build an ARM64 version of XEMU for windows.

While I know these sorts of things are very complicated and time consuming, I think it would be great to make this amazing emulator friendly with a lot of other platforms in windows. Thank you!

### Alternatives

_No response_

### Additional Context

There is a lot of promising ARM devices coming up this year, and it would be nice if XEMU was ahead in that sense... Other popular emulators have had ways to build for ARM or have ARM builds, like Dolphin, PPSSPP and Duckstation <3

### PR DESCRIPTION
**Pull request by mborgerson**
- [x] Fix updating/reporting SSL
- [x] Clean up `clock_gettime` and `QEMU_PACKED` hacks
- [x] Fix PDB gen
- [x] Rebase
~~- [ ] Actually strip binaries~~
- [x] Testing

I don't have an arm64 machine running Windows yet. Help from testers appreciated.

Progress towards #791

### CODE REVIEW

**Comment by FZXO11** [comment]
I think before adding the support for windows arm add the HardFPU for arm64 and make the releases have arm64 linux, windows 11 has arm64ec btw.

**Comment by mborgerson** [comment]
@FZXO11 xemu already provides aarch64 builds for Linux on Ubuntu, and building from source for other distributions is relatively easy for users.

As for hard fpu support for arm, as I have mentioned to you before it will happen but it's not the highest priority. If you want the feature faster, you are welcome to work on it and contribute improvements to the project.

**Comment by mborgerson** [comment]
cc: @holaimscott @RitschiRitsch @talynone @ArminiusTux @LilMisSierra

Do you want to give this arm build for Windows a try? You might need to install the [OpenGL compatibility pack](https://apps.microsoft.com/detail/9nqpsl29bfff?hl=en-US&gl=US).

**Comment by talynone** [comment]
> cc: @holaimscott @RitschiRitsch @talynone @ArminiusTux @LilMisSierra
> 
> Do you want to give this arm build for Windows a try? You might need to install the [OpenGL compatibility pack](https://apps.microsoft.com/detail/9nqpsl29bfff?hl=en-US&gl=US).

I downloaded the debug build artifact from here:
https://github.com/xemu-project/xemu/actions/runs/12541112761/artifacts/2370211994

It crashes on startup with the following message in the event log:


> Faulting application name: xemu.exe, version: 0.7.137.9, time stamp: 0x67720a79
> Faulting module name: xemu.exe, version: 0.7.137.9, time stamp: 0x67720a79
> Exception code: 0xc000001d
> Fault offset: 0x00000000007731fc
> Faulting process id: 0x1206C
> Faulting application start time: 0x1DB5AD2D8B7714D
> Faulting application path: C:\Emulators\xemu\xemu.exe
> Faulting module path: C:\Emulators\xemu\xemu.exe
> Report Id: 07788be3-b492-40b0-a0ab-84a17650b41d
> Faulting package full name: 
> Faulting package-relative application ID:

 
The x64 build from the same branch starts up properly.

**Comment by mborgerson** [comment]
@talynone Thanks for testing. Looks like I'll need to get a machine to debug it

**Pull request merged**
