### PR TITLE
nv2a: Check for CPU-modifications to textures before reusing

### LINKED ISSUE #457: Futurama: FMV videos are broken
### Title

https://xemu.app/titles/46490002/#Futurama

### Bug Description

All the game's FMV videos are broken.

### Expected Behavior

The videos plays normally

### xemu Version

0.6.1-7-g05d21c6e94

### System Information

_No response_

### Additional Context

_No response_

### LINKED ISSUE #937: Splinter cell: Broken loading screen image
### Title

https://xemu.app/titles/5553000c/#Tom-Clancy-s-Splinter-Cell

### Bug Description

Steps to reproduce:
load a level
press start
a corrupted image appears for a second

image

### Expected Behavior

There shouldn't be a corrupted image on the screen

### xemu Version

0.7.15

### System Information

CPU:          Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
OS Platform:  Linux
OS Version:   Manjaro Linux
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 970/PCIe/SSE2
Driver:       4.0.0 NVIDIA 510.68.02
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Fixes #457
Fixes #937 

[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/texture_cpu_update_tests.cpp)
[HW Results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Texture_CPU_Update)

### CODE REVIEW

**Comment by Triticum0** [comment]
It fixes SSX 3 and Commandos Strike Force intros
also fixes Darkwatch in-game cutscenes displaying

**Comment by Triticum0** [comment]
Doesn't fix any of the stuttery/laggy cutscenes =(

**Comment by abaire** [comment]
Thanks for testing!

I wouldn't expect this to have an effect on laggy videos, that'll need separate investigation/profiling to track down.

**Comment by Triticum0** [comment]
there a ton of games that have this issue do you what me to test them all?

**Comment by abaire** [comment]
No, given the number you've already verified I'm confident that this fix should cover most cases. 

If we find any games that still have frozen videos after this PR we should file new issues as they're likely some other cause.

**Comment by Triticum0** [comment]
looking there about 28 games

**Comment by Triticum0** [comment]
Also Will this fixes the intel issue. The same thing happen on intel GPU for the game that didn't have the issue on other GPUs

**Comment by abaire** [comment]
> Also Will this fixes the intel issue

I would not expect it to have any effect on hw-specific problems. This is just another case where xemu optimizations happen to do the wrong thing and need to be bypassed. I expect this will have some negative effect on performance since it's doing more work on the CPU than before, but hopefully not too bad.

**Comment by Triticum0** [comment]
ok I will do some more testing and see if I fix any issues. Also #735 fixed some of the remaining shadow bugs

**Comment by abaire** [comment]
> ok I will do some more testing and see if I fix any issues. Also #735 fixed some of the remaining shadow bugs

Cool, let's keep the discussions separate; you can add notes on that PR for games you find fixed or newly broken by that change.

**Comment by Triticum0** [comment]
already have

**Comment by RageXbox** [comment]
Confirmed that this fixes #937

**Comment by Triticum0** [comment]
This made Arctic Thunder FMV Laggy

**Comment by abaire** [comment]
> This made Arctic Thunder FMV Laggy

What is the behavior on master without the PR? Does the video play normally or is it just a frozen frame?

**Comment by Triticum0** [comment]
The video played normally, well aside from what I put on my report https://xemu.app/titles/4d570002/#Arctic-Thunder I just make it worse

**Pull request merged**
