### PR TITLE
nv2a: Test Append_skinning_code

### LINKED ISSUE #331: Append_skinning_code is Untested
### Title Information
https://xemu.app/titles/584d0003/#Championship-Bowling
https://xemu.app/titles/41510002/#Flight-Academy
https://xemu.app/titles/544b0001/#Magi-Death-Fight

### Bug Description
The games crashes with an assertion when going into gameplay
https://github.com/mborgerson/xemu/blob/6f477f02a653a0417c82dc3a1473b1bd3e96bca0/hw/xbox/nv2a/shaders.c#L276

### Expected Behavior
It should make it in-game

<h3>Version</h3>
<ul>
<li>Version: build-202106030108( <a href="https://github.com/mborgerson/xemu/commit/6f477f02a653a0417c82dc3a1473b1bd3e96bca0"><tt> 6f477f0</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

### Additional Context

[Magi-Death-Fight-Crash-Log.zip](https://github.com/mborgerson/xemu/files/7947587/Magi-Death-Fight-Crash-Log.zip)

### PR DESCRIPTION
**Pull request by RageXbox**
Removed the untested assert and 2 games got Ingame/Playable.
Championship Bowling
Screenshot_2022-01-17_203430

Magi Death Fight!
Screenshot 2022-01-27 155514

Fixes #331

### CODE REVIEW

**Comment by MasonT8198** [comment]
But is this accurate to real hardware, with a testing environment proving it?

**Comment by Ernegien** [comment]
Do you have comparison screenshots against real hardware? How confident are you this skinning code affects something that exists in these particular screenshots? Changing the skin code temporarily to something invalid might help you better witness this, but specific test cases would be ideal.

**Comment by RageXbox** [comment]
> Do you have comparison screenshots against real hardware? How confident are you this skinning code affects something that exists in these particular screenshots? Changing the skin code temporarily to something invalid might help you better witness this, but specific test cases would be ideal.

What do you mean by that?

**Comment by RageXbox** [comment]
Hardware
Screenshot_2022-01-17_203908

image

**Comment by Triticum0** [comment]
@RageXbox The assertion for Magi Magi Death Fight! happens when playing the story mode it hasn't been fixed.

**Comment by RageXbox** [comment]
> @RageXbox The assertion for Magi Magi Death Fight! happens when playing the story mode it hasn't been fixed.

Any image so I could find out.

**Comment by RageXbox** [comment]
> > @RageXbox The assertion for Magi Magi Death Fight! happens when playing the story mode it hasn't been fixed.
> 
> Any image so I could find out? What xemu branch are you using?

**Review by MasonT8198 — CHANGES_REQUESTED** [review]
This doesn't give enough evidence to support that this code actually is accurate to real hardware, writing a test case using nxdk or something of the sort would help prove this code functions as intended, see @abaire's pull requests and his test suite for some guidance

**Comment by mborgerson** [comment]
Thanks for the hardware comparison shots. I agree, it would be best to have a test case. However, since this unblocks games and looks correct, I'll merge now and we can revisit.

**Pull request merged**
