### PR TITLE
nv2a: Set oFog.x with most significant oFog mutation

### LINKED ISSUE #564: The need for speed series(excluding Need for Speed: Hot Pursuit 2) and MTX motorcross dont render correctly
### Title

https://xemu.app/titles/41560022/#MTX-Mototrax
https://xemu.app/titles/45410047/#Need-for-Speed-Underground
https://xemu.app/titles/4541005a/#Need-for-Speed-Underground-2
https://xemu.app/titles/4541007b/#Need-for-Speed-Most-Wanted
https://xemu.app/titles/4541009e/#Need-for-Speed-Carbon

### Bug Description

When going in-game for these games, all objects rendered on screen excluding car models are not correctly rendered this is present for all the games. Also Affects Menus if you manage to make it in-game (Menu don't render with the need for speed series).
Need for Speed Underground
Screenshot from 2021-11-21 17-25-54

Need for Speed Underground 2
Screenshot from 2021-11-21 17-25-36

Need for Speed Most Wanted
Screenshot from 2021-11-21 17-26-06
Step to reproduce:
1.Insert disk
2.Mash a to enter a race 

### Expected Behavior

It should render correctly

### xemu Version

Version: 0.6.2
Branch: master
Commit: 5faa241
Date: Sat Nov 20 08:53:11 UTC 2021
Last-known Working: Unknown

### System Information

Field | Value
-- | --
OS | Ubuntu 20.04.3 LTS
CPU | Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
Graphics Device | Mesa Intel(R) HD Graphics (BDW GT1)
Graphics Driver | Drivers: 4.6 (Core Profile) Mesa 21.0.3

### Additional Context

Video for issue are below:
[Need for Speed Underground](https://www.youtube.com/watch?v=2OWLHfFzUSQ)
[Need for Speed Underground 2](https://www.youtube.com/watch?v=vh6PFLvl_1c)
[Need for Speed Most Wanted](https://www.youtube.com/watch?v=fzoIA1uDxCA)

Big thank to guru emulation for the footage

### LINKED ISSUE #673: Need for Speed Underground: FMVs not rendered to screen
### Title

https://xemu.app/titles/45410047/#Need-for-Speed-Underground

### Bug Description

The intro FMV for Need For Speed: Underground is never rendered to the front buffer. Looking at the textures I can see that the movie is being loaded, just never blitted.

### Expected Behavior

The FMV should be visible during the intro.

### xemu Version

Version: 0.6.2-53-g6b821d2062
Branch:  master
Commit:  6b821d2062f28d8b04c7e02447ed066b50936eea
Date:    Mon Jan 24 09:41:21 PM UTC 2022

### System Information

OS: Kubuntu 21.04 - 5.11.0-38-generic
CPU: Core i7-6700K @ 4GHz
GPU: NVIDIA GeForce GTX 1070
GPU Driver: 4.6.0 NVIDIA 470.74

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Sets `oFog.x` to the most significant component modified by the vertex program, mimicking HW behavior.

[Tests](https://github.com/abaire/nxdk_pgraph_tests/blob/3c23adb4fcb6a059f42a34b76d0e931d1fb9cd30/src/tests/fog_tests.cpp#L329)
[HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Fog_coord_vec4)

Fixes #673 

Appears to fix #564 as well (testing with Need For Speed: Underground)

### CODE REVIEW

**Comment by Fabxx** [comment]
@abaire  Progress with this PR for both U1 and U2

nfsu1 fix
nfsu2

**Comment by LucioXerus** [comment]
For Need for Speed Most Wanted, the graphics in game seem to render ok. However, the cutscenes still don't play (black screen with sound) and there are is no menu so I can't see what to select once I go in game.
Nomenu

**Comment by jenci8888** [comment]
This game can be playable start to finish, but there's one issue: (In the future I will add compat list later once this PR merged)
- Texture layer on HUD? (You cannot to see mini-map where you're going in during pursuit, but racing is fine.)
- Weird rain texture on the HUD

image

**Comment by abaire** [comment]
@gamrXerus, @jenci8888  please report these issues as new bugs, they almost certainly have nothing to do with this PR and are separate issues related to the games themselves. You can use the new issue link for this repository and fill out the template for a title issue.

**Comment by mborgerson** [comment]
Hmm, interesting. Thanks!

**Pull request merged**
